apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics
  template:
    metadata:
      labels:
        service: analytics
    spec:
      containers:
        - name: analytics
          image: 371542176961.dkr.ecr.us-east-1.amazonaws.com/coworking-space:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: IMAGE_TAG
              valueFrom:
                configMapKeyRef:
                  name: my-env
                  key: IMAGE_TAG
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_PASSWORD
            - name: ECR-URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ECR-URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-env
                  key: DB_HOST
      restartPolicy: Always
      imagePullSecrets:
        - name: my-ecr-secret