apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
# This is not the actual password. Actual password
#  is stored in secret file by directly creating secrets using kubectl cli
#  eg. kubectl create secret generic my-secret --from-env-file=.env
  DB_PASSWORD: d293aW1zb3NlY3VyZQ==