apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
# This is not the actual password. Actual password
#  is stored in secret file by directly creating secrets using kubectl cli
#  eg. kubectl create secret generic my-secret --from-env-file=.env
  ECR-URL: d293aW1zb3NlY3VyZQ==

# Database password is used directly from postgres-password secret
# This secret is made by helm chart while installing postgres with the help of helm.

# For security purposes, it is recommended to maintain a .env file as is used above
# It helps prevent pushing the plain-text passwords directly to the repository.